### ISSUE TITLE
Rewrite Killing in the Name of... Quest (Grizzly Adams etc)

### ISSUE THREAD

**Issue by att3** [PrinterLUA/FORGOTTENSERVER-ORTS#1016]
I know there are plenty of somewhat related issues, but this issue should be for only 1 thing which is;
After you have finished task/s and and go to Grizzly Adams -> greet him and say "task"
If the task has boss Grizzly should say the "boss msg" which is different every time if I am not totally wrong.

Currently it seems to be written like when you say "report" and you have finished task he will give you the experience, storage etc.
But currently he doesn't say anything, even tho he should say this?
```
npcHandler:say("Awesome! you finished " .. (finished > 1 and "various" or "a") .. " task" .. (finished > 1 and "s" or "") .. ". Talk to me again if you want to start a {task}.", cid)
```

**Comment by HyphenMaster** [comment]
What is the progress on this issue?
