### ISSUE TITLE
[bulk] Map related issues

### ISSUE THREAD

**Issue by EPuncker** [PrinterLUA/FORGOTTENSERVER-ORTS#1200]
### Post about missing areas here!

*__Missing areas / Map Issues__
- [ ] Port Hope (Issue #686)
- [ ] Fix Venore Corym spawn
- [ ] Lion's Rock (recorded with TibiaCast)
- [ ] Oramond
- [ ] Sight of Surrender Area (Upper Roshamuul)
- [ ] Farmine Mage Tower (Issue #1503)

* __Houses__
- [ ] [Old Sanctuary of God King Qjell](http://tibia.wikia.com/wiki/Old_Sanctuary_of_God_King_Qjell)
- [ ] [Demon Tower (+ exact destination of the teleport)](http://tibia.wikia.com/wiki/Demon_Tower)

**Comment by EPuncker** [comment]
I don't think that we are able to enter temple of light anymore so I guess we can remove it from list?

**Comment by TheSumm** [comment]
It is accessible each November, isn't it?

**Comment by ninjalulz** [comment]
I have Temple of Light (but not good or bad side), but how the fuck do you even get there?

**Comment by EPuncker** [comment]
that is what I was talking about, it is not possible to go outside of it anymore, neither by winning or losing the event, I've tried it last november
