### ISSUE TITLE
skip tutorial option

### ISSUE THREAD

**Issue by dgprado** [PrinterLUA/FORGOTTENSERVER-ORTS#1505]
Add skip tutorial option in tutorial sland.

**Comment by EPuncker** [comment]
inaccessible, only dawnport and rookgaard are accessible now, what about removing this map and scripts? xD I really want that removed since I can't open my server kk

**Comment by TheSumm** [comment]
It is accessible if you got a character there.
There is no point in removing the island and once we got dawnport we can add config so users may choose what to use (tutorial / rookgaard / dawnport)
