### ISSUE TITLE
The Ape City Quest issue

### ISSUE THREAD

**Issue by huxizz** [PrinterLUA/FORGOTTENSERVER-ORTS#1537]
Hello there
i found that mission 4 didnt work in The Ape City Quest
i found that changing the
 if player:getStorageValue(Storage.TheApeCity.Questline) == 8

to

if player:getStorageValue(Storage.TheApeCity.Questline) == 7
in movements\scripts\the ape city\Mission4ParchmentDecyphering.lua
fixed it.

**Comment by ninjalulz** [comment]
Thanks!
