### ISSUE TITLE
Map from rar to 7zip

### ISSUE THREAD

**Issue by dragaoart** [PrinterLUA/FORGOTTENSERVER-ORTS#1541]
I'm having some issues with unrar on my vps. 
I would like to suggest to compress it on a 7zip compression method, since the map.rar compression do not uncompress with unrar-free on ubuntu.

--edit
This process also saves almost 10mb of space.

**Comment by novasdream** [comment]
each version of compressed item have total size of file..
each version of OTBM have only a little diff.

I dont knoiw why use rar files..
