### ISSUE TITLE
Error XML HOUSES

### ISSUE THREAD

**Issue by TeFoOBr** [PrinterLUA/FORGOTTENSERVER-ORTS#1543]
in last update, one error occurred ...houses
![sem titulo](https://cloud.githubusercontent.com/assets/10349474/5712127/c7ee6978-9a96-11e4-9a48-7eacd685b479.png)

**Comment by ninjalulz** [comment]
It loads just fine for me.

**Comment by EnzzoCaaue** [comment]
here is not bugged '-'
