### ISSUE TITLE
can someone track that and add it to the map?

### ISSUE THREAD

**Issue by pitis91** [PrinterLUA/FORGOTTENSERVER-ORTS#1544]
Lion's heart new Darashian resp.
tibiacast:recording:2369808?title=Lion's%20Rock%20Quest%20

**Comment by ninjalulz** [comment]
I have already recorded this, and will add it once there is an official items.otb available.

**Comment by pitis91** [comment]
ah thanks ninja I don't know that =P I think the same is oramond?
