### ISSUE TITLE
bug on senja castle lever

### ISSUE THREAD

**Issue by pitis91** [PrinterLUA/FORGOTTENSERVER-ORTS#1545]
when you use the lever the first time nothing happend, when you use it disapear the walls but also the lever.

17:26 You see a lever.
ItemID: [1945], ActionID: [4210].
Position: [X: 32180] [Y: 31633] [Z: 8].

17:28 You see white marble floor.
ItemID: [406].
Position: [X: 32180] [Y: 31633] [Z: 8].

and this item must be a normal spellbook.

17:29 You see Dragha's spellbook.
It weighs 58.00 oz.
It apparently belonged to someone called Dragha, the apprentice of a voodoomaster.
ItemID: [6120].
Position: [X: 32187] [Y: 31624] [Z: 4].

senja village mapbugs.
17:32 You see a closed door.
It is locked.
ItemID: [1210].
Position: [X: 32132] [Y: 31658] [Z: 7].
but you can open it:
17:33 You see an open door.
ItemID: [1211].
Position: [X: 32132] [Y: 31658] [Z: 7].

**Comment by ninjalulz** [comment]
What do you mean by "when you use the lever the first time nothing happend"?

**Comment by pitis91** [comment]
the magic walls not disapear the first time that you use it
