### ISSUE TITLE
draconia mapbug

### ISSUE THREAD

**Issue by pitis91** [PrinterLUA/FORGOTTENSERVER-ORTS#1546]
there are 2 keys there, the needed to continue and another theodore's love
17:54 You see a silver key (Key:3007).
It weighs 1.00 oz.
ItemID: [2088], ActionID: [3007].
Position: [X: 32813] [Y: 31576] [Z: 5].
17:52 You see Theodore Loveless' key.
It weighs 1.00 oz.
It is the key to his private room.
ItemID: [8762].
Position: [X: 32813] [Y: 31576] [Z: 5].

**Comment by ninjalulz** [comment]
Thanks
