### ISSUE TITLE
Pythius The Rotten Quest not working

### ISSUE THREAD

**Issue by Zeotix** [PrinterLUA/FORGOTTENSERVER-ORTS#1561]
the npc Pythius The Rotten.lua have problem in the line 51 of golden mug
elseif msgcontains(msg, "golden mug") then
if npcHandler.topic[cid] == 4 then    <<<<<<  in the npchandler.topic must be == 5 then

and the mission when you use the pick on the rock, the lava is not transformed and the portal does not close:
![pithus the rotten](https://cloud.githubusercontent.com/assets/7542541/5849508/b910b244-a1bc-11e4-8c68-c943e19349e0.png)

also makes a missing creatureEvent if you kill the Pythius The Rotten nothing happens you get caught in the mission.The emergency exit portal is wrong teleports you to the portal that opens out and that causes them to make another Pythius The Rotten and other more and more each time you try out

I apologize for my English do my best to try to help and look for errors. thanks

**Comment by ninjalulz** [comment]
Can you verify if these changes works properly or not?

**Comment by Zeotix** [comment]
I did a test okay to start but when you end up killing Pythius The Rotten do not teleport to the other side which is chest just missing it now...
i have this script for creatureevent change this for tfs 1.0/1.1:

function onKill(cid, target, damage, flags)
	if(isMonster(target)) then
		if(string.lower(getCreatureName(target)) == "pythius the rotten") then
			doTeleportThing(cid, {x=32577, y=31403, z=15})
			doSendMagicEffect(getCreaturePosition(cid), CONST_ME_TELEPORT)
			doCreatureSay(target, "NICE FIGHTING LITTLE WORM, YOUR VICTORY SHALL BE REWARDED!", TALKTYPE_ORANGE_1)
			setPlayerStorageValue(cid, 12609, 3)
		end
	end
	return true
end
