### ISSUE TITLE
items.otb is outdated?, why?

### ISSUE THREAD

**Issue by pitis91** [PrinterLUA/FORGOTTENSERVER-ORTS#1570]
I'm just trying to get tinder box, melting horn and fireproof horn id's. that items are from 10.37 items.otb.
I've Downloaded a precompiled 10.53 TFS 1.0 from 30 September.
And I've get the items ids from their items.otb (It's unnoficial? or what?) I'm just working on tinderbox quest.
I'm tested on official TFS 1.1 (last build compiled from nightlites) works fine.
I can Get us my items.otb
Download: https://www.mediafire.com/?43w888b6yfww3g8

there are the items to add into items.xml

	<item id="22719" article="a" name="melting horn">
		<attribute key="description" value="A hermit near Carlin might be able to tell you more about it." />
		<attribute key="weight" value="200" />
	</item>
	<item id="22720" article="a" name="fireproof horn">
		<attribute key="description" value="It's very sturdy and could even be considered fireproof." />
		<attribute key="weight" value="200" />
	</item>
	<item id="22721" article="a" name="tinder box">
		<attribute key="weight" value="200" />
	</item>
	<item id="22722" article="a" name="frozen ursagrodon" />
	<item id="22723" article="a" name="frozen ursagrodon" />
	<item id="22724" article="a" name="frozen ursagrodon" />

**Comment by ninjalulz** [comment]
It is unofficial.
