### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by ninjalulz** [PrinterLUA/FORGOTTENSERVER-ORTS#1573]
There has been numerous reports regarding malfunctioning quests or NPCs and map bugs in our issue tracker and in our thread on OTLand.

We strive for accuracy and that's why it may take a while to complete certain quests or NPCs. With help from third-parties (you) it may speed up the process.

So what can you do to help? Provide us with either **Quest Logs** or **NPC transcripts**.

If there is any important map areas we are currently missing (e.g **Sight of Surrender** (*Upper Roshamuul*), **Caveman Shelter** or **Old Sanctuary of God King Qjell**), then you can help us by either track it yourself, or provide us with a TibiaCast recording (the version doesn't matter).

**Comment by PrinterLUA** [comment]
Agree :+1:

**Comment by Tazer89** [comment]
Ninja, PrinterLUA kontakta mig på skype: linusbrandt

Har frågor hur ni vill man ska lägga upp nya quests/mission och vilka storages ni vill man ska andvända.

**Comment by Schiffers** [comment]
well, astant in otland have all roshamuul....
we can try ask to him about this ... 
caveman shelter, is where?
old sanctuary i have in one map, i will share later

**Comment by att3** [comment]
Some questlogs (not all 100% perfect e.g, "hive war points")
http://pastebin.com/w4dqrCVy

All these quest-logs are taken from youtube video records.

**Comment by Schiffers** [comment]
very nice, lower roshamuul :3 nice!!!
I have the log of shadows of yalahar, have here?
if not, tell me

**Comment by att3** [comment]
No we don't, please show yours

**Comment by Schiffers** [comment]
http://pastebin.com/22HwpYm8

**Comment by att3** [comment]
That isn't from real tibia right?

@ninjalulz said "We strive for accuracy"
As I understood it, we don't want to write quest logs ourselves.

**Comment by Schiffers** [comment]
well, i will see on my character if is like this, wait, i will back with feedback

**Comment by Schiffers** [comment]
here are the quest log of completed quest shadows of yalahar...
http://i.imgur.com/Zg5pwBn.png

**Comment by tarantonio** [comment]
there is a datapack in otland with most of the issues of this datapack solved, plus map areas missing on  the .otbm:
http://otland.net/threads/global-ot-oramond.226045/page-2#post-2189058

**Comment by ninjalulz** [comment]
I'm aware of that data pack but I won't add anything from it. Which areas too be precise? All I could find were Oramond which will be added once there is an official otb for 10.5x+

**Comment by pitis91** [comment]
@ninjalulz the datapack mentioned there have full chyllfrost undergrounds. (svargrond new temporal glacial mountain)

**Comment by ninjalulz** [comment]
I see, I didn't bother to check that area. :smiley: 

Is there anything else I overlooked?

**Comment by pitis91** [comment]
also i've seen full new island of destiny look

**Comment by ninjalulz** [comment]
Thanks, I'll add those later then xD

**Comment by Schiffers** [comment]
i have one question, all people, all time say about "an official otb 10.5X, but why don't make this more fast? tibia real are in 10.72, why can't add a otb official, and why not have a advance in tfs 1.1, for versions :S in another times the ots was like tibia real, tibia real 8.4x ots was 8.3 not doing we wait too much time... don't understand why the mark don't update the tfs with new things.. but is ok, tibia will die with the time

**Comment by pitis91** [comment]
I think the only thing for mark don't open his sources is obvious we have better things than shadowbot and same...

**Comment by Schiffers** [comment]
scared with lost the public in the his ots...i think, not is certly :P

**Comment by tarantonio** [comment]
It has also working warzones, WOTE, Chayenne Realm Quest, Grey Island underground...

**Comment by ninjalulz** [comment]
Warzones (I'm in the process of rewriting bigfoot's burden quest anyway), and WOTE should be working already. It is the same Hive underground I added months ago so it's nothing new.  xD

I simply cut out everything I want and then paste it to this one.

**Comment by tarantonio** [comment]
how do you paste on the same position as original?
