### ISSUE TITLE
The Shattered Isles Quest Dead body

### ISSUE THREAD

**Issue by Tazer89** [PrinterLUA/FORGOTTENSERVER-ORTS#1574]
Position: [X: 32093] [Y: 32574] [Z: 8].

Shall loot Dragha's spellbook for the quest: The Shattered Isles Quest.

**Comment by Royalot** [comment]
The part with The Counterspell quest was still WIP but:
Maybe if someone edit the map he can add:
{x = 32093, y = 32574, z = 8} for the corpse
item id="6120" with aid=2000 and uid=12710 

and aid 12710 to the energyfields:
{x = 32091, y = 32577, z = 8}
{x = 32091, y = 32576, z = 8}
{x = 32091, y = 32575, z = 8}

**Comment by Tazer89** [comment]
Should be awesome, best is if @ninjalulz does it :)
