### ISSUE TITLE
Is this just me or?

### ISSUE THREAD

**Issue by att3** [PrinterLUA/FORGOTTENSERVER-ORTS#1576]
Doing /i vial, (subtype) it will create vial of unknown.
Same thing happens if I buy it e.g from Sandra same thing happens.
Also if I drop the liquids on the floor it's still unknown.

Is this onLook issue or is it TFS (sources) issue?

**Comment by ninjalulz** [comment]
I think it's just you, I can't reproduce this with latest TFS.

**Comment by att3** [comment]
Ok, thanks :)
