### ISSUE TITLE
Problem or Not ?

### ISSUE THREAD

**Issue by TeFoOBr** [PrinterLUA/FORGOTTENSERVER-ORTS#1584]
these days you guys altered some scripts related to position (north, south, east, west)	
players:setDirection(EAST) for players:setDirection(DIRECTION_EAST) for example
in items.xml the beds are with
	attribute key="partnerDirection" value="east"
this part does not need to be changed? has no connection?

item id = 7778 to 7822
ty

**Comment by ninjalulz** [comment]
No, it doesn't need to be changed.

[tools.cpp](https://github.com/otland/forgottenserver/blob/master/src/tools.cpp#L296-319)
