### ISSUE TITLE
Quentin & Rock With A Soft Spot

### ISSUE THREAD

**Issue by Popzi** [PrinterLUA/FORGOTTENSERVER-ORTS#1597]
After recent commit:

[Warning - NpcScript::NpcScript] Can not load script: Quentin.lua
data/npc/scripts/Quentin.lua:18: '}' expected (to close '{' at line 12) near ')'
[Warning - NpcScript::NpcScript] Can not load script: Rock With A Soft Spot.lua
data/npc/scripts/Rock With A Soft Spot.lua:70: ')' expected near 't'

Only errors after the fix commit.

Rock With A Soft Spot has a untrailed ' on line 70.
"don't" should be "don\'t"
npcHandler:setMessage(MESSAGE_GREET, 'Welcome, this is the {Gray Beach temple}, |PLAYERNAME|. Whether you are wounded, poisoned - or wait, don\'t tell me - yes, this is probably a case of being more emotionally hurt, I will do my best to {heal} you.')

Quentin I am uncertain, do we need all of this with several keywordhandlers?
https://github.com/PrinterLUA/FORGOTTENSERVER-ORTS/blob/99f8c48855620ad6e6908ec0aa2b1ade2cec4e47/data/npc/scripts/Quentin.lua#L12,#L33

**Comment by TheSumm** [comment]
It is one keywordhandler with different keywords depending on which condition you match.

**Comment by Popzi** [comment]
But when speaking to Quentin, 

keywordHandler:addKeyword({'wooden stake'}, StdModule.say, {npcHandler = npcHandler, text = 'A blessed stake? I don\'t believe in things like that. If anyone does, it\'s probably old Quentin.', reset = true})

He is Quentin ? :confused:

**Comment by TheSumm** [comment]
The conditions are these
```
function(player) return player:getStorageValue(Storage.FriendsandTraders.TheBlessedStake) == -1 end)
```

But that is probably a wrong transscript too.

**Comment by ninjalulz** [comment]
Alright, the errors has been fixed now. About the transcripts, it will be fixed in the future. Feel free to hook us up with proper transcripts et cetera.

**Comment by TheSumm** [comment]
I think I have the full transscript, I can do it soon.
