### ISSUE TITLE
Raids! Serpent spawn raid is bugged.

### ISSUE THREAD

**Issue by dahe0216** [PrinterLUA/FORGOTTENSERVER-ORTS#1598]
The serpent spawns are spawning west of darashia in drefia :) I could fix but actually dont know the spawn pos of it .. :S

Not sure if there are more, but seems like all "old" raids should be reviewed

**Comment by att3** [comment]
Copying my comment I posted here:
https://github.com/PrinterLUA/FORGOTTENSERVER-ORTS/issues/1055

Not sure if have been fixed, or if there's another issue already open for this, but I am pretty sure that some raids are fucked up.

Example, 30 or even more necromancers spawn(raid) at edron, near the stones where Orshabaal raid occurs.
Another one I seen was that there were serpent spawns spawning(raid) at Drefia "ground floor"
> Yep (necromancer at edron), https://github.com/PrinterLUA/FORGOTTENSERVER-ORTS/blob/546616d8f4537f73b28573def323fc81af46bf07/data/raids/Ankrahmun/Necromancer.xml

> (serpent spawn at Drefia)
https://github.com/PrinterLUA/FORGOTTENSERVER-ORTS/blob/546616d8f4537f73b28573def323fc81af46bf07/data/raids/new/sspawn.xml

Not sure if there are more, but seems like all "old" raids should be reviewed
