### ISSUE TITLE
Drowning doesn't get removed

### ISSUE THREAD

**Issue by att3** [PrinterLUA/FORGOTTENSERVER-ORTS#1599]
I don't know why it doesn't get removed, the "step out" code gets executed, 
player:removeCondition(CONDITION_DROWN)

Doesn't remove it (on that event)

But e.g temple npc's do remove conditions even though they are using the same 
player:removeCondition(CONDITION)

**Comment by ninjalulz** [comment]
It works just fine for me.

**Comment by walissonsantos** [comment]
I also have the same problem, if in and out of quara the condition is infinite.

**Comment by ninjalulz** [comment]
Which quara spawn are you talking about?

**Comment by att3** [comment]
Hm, that's very strange.
Got any idea what could be the cause for me?
Although the player:removeCondition(CONDITION) (stepOut) get's executed it doesn't seem to remove the condition.

**Comment by walissonsantos** [comment]
sorry, Spawn Sea Serpent in Svargrond.

**Comment by ninjalulz** [comment]
It returns a nil value when you enter the teleports at Sea Serpents, and the ticks is set to -1 (infinite) while it should only last for a couple of seconds. I'll fix it later.
