### ISSUE TITLE
3th seal is broken for the bansuee quest.

### ISSUE THREAD

**Issue by viperthepala** [PrinterLUA/FORGOTTENSERVER-ORTS#1600]
Levers of the 3th seal dont work.

**Comment by viperthepala** [comment]
currently going trough the enteir quest also the magic walls wich can be disabled dont reappair after going trough the hall in the starting.

**Comment by viperthepala** [comment]
Also the invisible wall preventing you to walk past on normal level at the coordenates below, is not in place.:
21:58 You see dirt floor.
ItemID: [9025].
Position: [X: 32266] [Y: 31896] [Z: 12].
21:58 You see dirt floor.
ItemID: [9022].
Position: [X: 32265] [Y: 31896] [Z: 12].
21:58 You see stones.
ItemID: [3614].
Position: [X: 32267] [Y: 31896] [Z: 12].

**Comment by viperthepala** [comment]
whats up with closing all pull requests/open issue's as this is still not fixed.

**Comment by dbjorkholm** [comment]
We have moved the development to a new [repository](https://github.com/orts/server).
