### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by YohanAugusto** [PrinterLUA/FORGOTTENSERVER-ORTS#880]
When you finish task and say "report" to Grizzly your task start counting again from 0. But if you kill a monster it wont get counted. Teleports to bosses doesn't work.

**Comment by att3** [comment]
This is quite minor issue. (meaning easy fix)

Questlog stays because when you report the task to Grizzly he will set your storage ("STORAGE", 0)
Instead of ("STORAGE", -1)
