### ISSUE TITLE
Rookgaard to separated map as Yasir

### ISSUE THREAD

**Issue by EPuncker** [PrinterLUA/FORGOTTENSERVER-ORTS#908]
please FFS remove rookgaard from map and add it as yasir maps are added at least, so we can still have a clean map and maybe even a setting to set it on/off with it added that way xD

**Comment by EPuncker** [comment]
I want to bump this one @PrinterLUA since my poor PC can't load the map now that it is that big and I want to start contributing with this project again xD

**Comment by ninjalulz** [comment]
This would require a new function, e.g Game.loadSpawn("path/to/spawn.xml") because Game.loadMap doesn't load spawns.

**Comment by EPuncker** [comment]
that is sad, and the saddest thing is that 99% of those guys who cried asking for rookgaard are not even using it, or doesn't even have a server anymore lol xD

**Comment by ninjalulz** [comment]
Hypothetical, which areas should be separated from the map?

- Rookgaard
- Spirit Grounds
- Forsaken Mines (Cyclops)

I was thinking The Spike as well, since it's a big area.

**Comment by EPuncker** [comment]
the spike are is kinda useful because of addons and easy tasks, the rest can be take out I guess
